menu:
  归档: /archives
  分类: /categories
  关于: /about
  订阅: /atom.xml

# Table of contents | 文章目录
toc:
  on: true
  list_number: false # 目录序号
  max_depth: 3  # 1 - 6 (h1-h6) 目录最大级数

# gitment
gitment: false
gitment_owner:
gitment_repo:
gitment_client_id:
gitment_client_secret:

# gitalk
gitalk: false
gitalk_owner:
gitalk_admin: []
gitalk_repo:
gitalk_client_id:
gitalk_client_secret:

# valine comment
valine: false
leancloud_id:
leancloud_key:

# disqus comment
disqus: false
giscus:
  repo: fengz63/fengz63.github.io         # 你的仓库
  repo_id: R_kgDONkh1Vg                   # giscus.app 生成的 repo ID
  category: Q&A                           # 你创建的分类名
  category_id: DIC_kwDONkh1Vs4Cuqet       # giscus.app 生成的 category ID
  mapping: pathname                       # 建议用 pathname 或 slug
  theme: light                            # 可选: light / dark / preferred_color_scheme

# google analytics
googleTrackId: G-J38N5N288S

# whether to show read more button when showing article in excerpt in main page
read_more_btn: true
